---
title: "Expert Feedback Analysis"
output: html_notebook
---
```{r}
library(tidytext)
library(tidyr)
library(ggplot2)
library(dplyr)
library(car)
library(reshape2)
```
```{r}
#read in data
all_comments <- read.table("data/all_feedback.tsv", fill=TRUE, header=TRUE, sep="\t", quote="", comment.char="")

#sort by comment length
all_comments <- all_comments[order(all_comments$Length),]
head(all_comments)

#remove comments that haven't been rated yet
all_comments <- all_comments %>%
  na.omit()
head(all_comments)
```

```{r}
#specific, actionable, justified counts
feedback_sum <- summarise(all_comments,
                          condition="x",
                          wordcount = mean(Length),
                          wordcount_sd = sd(Length),
                          none = length(which(Specific==0 & Actionable==0 & Justified==0))/length(Comment),
                          specific_only = length(which(Specific==1 & Actionable==0 & Justified==0))/length(Comment),
                          specific_actionable = length(which(Specific==1 & Actionable==1 & Justified==0))/length(Comment),
                          specific_justified = length(which(Specific==1 & Actionable==0 & Justified==1))/length(Comment),
                          specific = length(which(Specific==1))/length(Comment),
                          actionable = length(which(Actionable==1))/length(Comment),
                          justified = length(which(Justified==1))/length(Comment),
                          all = length(which(Specific==1 & Actionable==1 & Justified==1))/length(Comment))

feedback_sum
```
```{r}
df <- melt(feedback_sum[,c('condition','none','specific','actionable','justified','all')], id.vars=1)
df

ggplot(df, aes(variable, value)) +
  geom_bar(stat="identity",position="dodge") +
  theme_bw() +
  scale_y_continuous(name="Proportion of Comments", limits=c(0,1)) +
  scale_x_discrete(name="Categories")
```
```{r}
#correlation of comment length and quality rating
ggplot(all_comments, aes(x=Sum, y=Length)) + 
  geom_point() +
  theme_bw()

plot(all_comments$Length)
```

```{r}
comment_text <- all_comments %>%
  mutate(feedback = as.vector(all_comments[,1]),
         linenumber=1:n())
  
comment_text
```
```{r}
#text analysis by bigrams
ngrams <- comment_text %>%
  unnest_tokens(ngram, Comment, token="ngrams",n=3)

ngrams
```
```{r}
separate_ngrams <- ngrams %>%
  separate(ngram, c("word1","word2","word3"), sep=" ")

separate_ngrams

mystop <- data.frame(words=c("the", "of", "that", "and", "it","at", "a", "as", "to","as","if","is","from", "on"))
ngram_filtered <- separate_ngrams %>%
  filter(!word1 %in% mystop$words) %>%
  filter(!word2 %in% mystop$words) %>%
  filter(!word3 %in% mystop$words)

ngram_filtered
```
```{r}

```


